# Generated by Django 2.0.4 on 2018-04-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='importance',
        ),
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
