# Generated by Django 2.0.4 on 2018-04-16 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180416_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
            preserve_default=False,
        ),
    ]
